# Chirpy Jekyll Theme Configuration
remote_theme: cotes2020/jekyll-theme-chirpy

# Site settings
lang: en

# Basic info
url: "https://rolodexter.github.io/rolodexter"
title: "rolodexter"
description: "Knowledge repository and modular intelligence mesh"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Chirpy options
# (Add more as needed from Chirpy documentation)
